### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by Fzoltan87** [pgooood/filger#2]
Hy Pavel,

Filger install not working. I work at localhost.

My folder structure:
![folder-structure](https://user-images.githubusercontent.com/16391914/103751183-325f5100-5008-11eb-860f-f0664a8249c8.jpg)

tinymce
  - filger folder
  - tinymce folder
  - upload folder
  index.php

Settings XML:
  -tinymce/filger/assets/xml/config.xml

```
<?xml version="1.0" encoding="utf-8"?>
<config>
	<upload>
		<path>../upload/</path>
		<url>localhost/tinymce/upload/</url>
		<uploader>assets/jQuery-File-Upload/jQuery-File-Upload-master/</uploader>
	</upload>
	<locale>
		<lang>en_US</lang>
		<date>d.m.Y H:i:s</date>
		<dec_point>.</dec_point>
		<thousands_sep>,</thousands_sep>
		<win_cp>windows-1252</win_cp>
		<dos_cp>CP437</dos_cp>
	</locale>
	<file_upload>
		<max_number_of_files>99</max_number_of_files>
		<accept_file_types>/.+\.(jpe?g|png|gif|pdf|docx?|xlsx?|txt|zip)$/i</accept_file_types>
		<max_file_size>2097152</max_file_size>
	</file_upload>
	<authenticator>auth.php</authenticator>
</config>
```

Index.php:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap 4 Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body id="body-top">
	<div class="container">
		<textarea class="tinymce">Hello World!</textarea>
	</div>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	<script src="http://localhost/tinymce/tinymce/tinymce.min.js"></script>
	<script>
		tinymce.init({
			selector: 'textarea.tinymce',
			height: 250,
			plugins: ['link image code'],
			toolbar: 'link image | code',
			menubar:false,
			statusbar:false,
			content_style:'body{font-size:14px !important;}',
			external_plugins: {
				'filger': 'http://localhost/tinymce/filger/assets/js/filger.tinymce.plugin.js'
			}
		});
	</script>
</body>
</html>
```

**I open the installer and an error occurs (http://localhost/tinymce/filger):**

`open($zipPath) === true && $zip->extractTo(FILE_UPLOAD_DIR) ){ $zip->close(); if(is_dir($path = FILE_UPLOAD_DIR.'jQuery-File-Upload-master/')){ $xml = new \pgood\xml\xml('assets/xml/page.xml'); if(!$xml->de()) $xml->append($xml->create('page')); $xml->de()->fileUploaderPath = $path; $error = !$xml->save(); //remove danger files foreach(scandir($dir = $path.'server/') as $item){ if($item == '.' || $item == '..') continue; if($item == 'php'){ if(is_file($pathUploader = $dir.'/'.$item.'/index.php')) rename($pathUploader,$pathUploader.'.bak'); }else removeDir($dir.'/'.$item); } } unlink($zipPath); } if($error){ echo str_replace(array('%HOME_URL%','%DOWNLOAD_URL%','%UNPACK_DIR%') ,array($fileUploadHomePage,$fileUploadDownloadUrl,FILE_UPLOAD_DIR) ,_('An error has occurred while installing jQuery File Upload. You can download and unpack it manually to "%UNPACK_DIR%" directory.')); }else{ echo str_replace(array('%HOME_URL%','%OK_URL%') ,array($fileUploadHomePage,parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH)) ,_('jQuery File Upload successfuly installed. Ok')); } }else{ echo str_replace(array('%HOME_URL%','%INSTALL_URL%') ,array($fileUploadHomePage,parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH).'?install=1') ,_('jQuery File Upload required. Try to download and setup it automatically.')); } ?>`

**Comment by pgooood** [comment]
Hi! Do you have php_zip extension enabled?
https://www.php.net/manual/en/zip.installation.php

**Comment by Fzoltan87** [comment]
Hy, Yes php_zip enabled.

![zip_en_2](https://user-images.githubusercontent.com/16391914/104120366-8df64b00-5336-11eb-8e7c-2246eb625b6d.png)

![zip_en](https://user-images.githubusercontent.com/16391914/104120367-8e8ee180-5336-11eb-88c9-ce86f9cf187e.png)

**Comment by pgooood** [comment]
Unfortunately, I cant reproduce your error. Actually it doesnt look like an error it is just a PHP source code from the include/install.php file. Usually it happens if there is no working PHP on the web server at all.

**Comment by Fzoltan87** [comment]
Hy. Hmmm, the php is running in localhost XAMPP Control Panel v3.2.3
Okay, I'll check it on a server.
